version: '3.3'

services:
  pts-db:
    image: mysql:5.7
    container_name: pts-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'pts'
      MYSQL_USER: 'pts'
      MYSQL_PASSWORD: 'pts'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    ports:
      - 3307:3306
    expose:
      - '3306'
    volumes:
      - pt-db:/var/lib/mysql
  
volumes:
  pt-db: